services:

  HeimrichHannot\CspBundle\:
    resource: '../src/{Controller,Csp,EventListener}/*'
    autowire: true
    autoconfigure: true
    bind:
      Nelmio\SecurityBundle\ContentSecurityPolicy\PolicyManager: '@nelmio_security.policy_manager'