services:

  HeimrichHannot\CspBundle\:
    resource: '../src/{Csp,EventListener}/*'
    autowire: true
    autoconfigure: true
    bind:
      Nelmio\SecurityBundle\ContentSecurityPolicy\PolicyManager: '@nelmio_security.policy_manager'

  HeimrichHannot\CspBundle\Controller\CspReporterController:
    arguments:
      - '@contao.framework'
      - '@?nelmio_security.csp_reporter_controller'
    tags:
      - controller.service_arguments